#!/bin/bash
# Execute lab download once, now
# Version 2025.06.17

# Check if a parameter is passed
if [ -z "$1" ]; then
	/bin/echo "Error: No service name provided. Please provide 'rover', 'dcare' etc."
	/bin/echo "	Usage: $0 [ rover | dcare | alphalab | medhealth ]"
	/bin/echo ""
	exit 1
fi

# Use the parameter to determine which service to run
SERVICE=$1

# Identify corresponding container
case "$SERVICE" in
	rover)
		CONTAINER="gofetchrover-rover-1"
		/bin/echo "'"$SERVICE"' corresponds to docker container: "$CONTAINER
		;;
	dcare)
		CONTAINER="gofetchrover-dcare-1"
		/bin/echo "'"$SERVICE"' corresponds to docker container: "$CONTAINER
		;;
	mule)
		CONTAINER="gofetchrover-muled-1"
		/bin/echo "'"$SERVICE"' corresponds to docker container "$CONTAINER
		;;
	medhealth)
		CONTAINER="gofetchrover-medhealth-1"
		/bin/echo "'"$SERVICE"' corresponds to docker container "$CONTAINER
		;;
	alphalab)
		CONTAINER="gofetchrover-alphalab-1"
		/bin/echo "'"$SERVICE"' corresponds to docker container "$CONTAINER
		;;
	*)
		/bin/echo "'"$SERVICE"' does not correspond a known container."
		;;
esac


# Validate the service name
if [ "$SERVICE" != "rover" ] && [ "$SERVICE" != "dcare" ] && [ "$SERVICE" != "mule" ] && [ "$SERVICE" != "medhealth" ] && [ "$SERVICE" != "alphalab" ]; then
	echo "Error: Invalid service name. Please provide either 'rover', 'dcare', 'medhealth', or 'alphalab'."
	exit 1
fi

# Check if container is running
if [ "$( docker container inspect -f '{{.State.Running}}' $CONTAINER )" != "true" ]; then
	/bin/echo ""
	docker ps -a
	/bin/echo ""
	/bin/echo "Error: '"$CONTAINER "' is not running. Unable to execute command in docker container!"
	/bin/echo "	Please 'docker start "$CONTAINER"' first."
	exit 1
fi

# Trigger lab download once
case "$SERVICE" in
	rover)
		/bin/echo "	...triggering one time lab download with Rover...now..."
		docker exec -it $CONTAINER python /app/api_rover.py
		;;
	dcare)
		/bin/echo "	...triggering one time lab download with Dynacare...now..."
		docker exect -it $CONTAINER python /app/dcare.py
		;;
	mule)
		/bin/echo "	...nothing for Mule yet...."
		docker exec -it $CONTAINER /bin/echo "		(/app/app-start.sh)"
		;;
	medhealth)
		/bin/echo "	...triggering one time lab download with Med-Health Labs...now..."
		docker exect -it $CONTAINER python /app/sftp_gofetch.py
		;;
	alphalab)
		/bin/echo "	...triggering one time lab download with AlphaLabs...now..."
		docker exect -it $CONTAINER python /app/sftp_gofetch.py
		;;
	*)
		/bin/echo "Invalid option: "$SERVICE
		;;
esac

/bin/echo ""
